### ISSUE TITLE
NameError in multidb.py

### ISSUE THREAD

**Issue by dieckmdo** [danielnyga/pracmln#15]
I am trying the object-recognition example with a bigger database (multiple dbs) and running the learner gives me the following error when `multicore` is enabled. Disabling ```multicore``` yields no error. Where does ```first```  come from and how can I solve this? 

```mlnlearn
mlnlearn.py (1077): update_config
==================
PRAC LEARNING TOOL
==================
 
loaded 50 database(s).
Parameter:                   Value:
---------------------------  -----------------------------------------------
db                           50 Databases
discr_preds                  0
epreds
grammar                      PRACGrammar
ignore_unknown_preds         0
ignore_zero_weight_formulas  1
incremental                  0
logic                        FirstOrderLogic
method                       CLL
mln                          <pracmln.mln.base.MLN object at 0x7fb43cb0ff10>
multicore                    1
output_filename              learnt.cll.scenes-new-object-detection.mln
params
pattern
prior_mean                   0
prior_stdev                  10
profile                      0
qpreds
save                         1
shuffle                      0
use_initial_weights          0
use_prior                    1
verbose                      1
setup learners...
[■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■] 100.000 % Traceback (most recent call last):
  File "/home/dominik/.local/lib/python2.7/site-packages/pracmln/mlnlearn.py", line 1167, in learn
    result = learning.run()
  File "/home/dominik/.local/lib/python2.7/site-packages/pracmln/mlnlearn.py", line 406, in run
    mlnlearnt = mln.learn(dbs, self.method, **params)
  File "/home/dominik/.local/lib/python2.7/site-packages/pracmln/mln/base.py", line 424, in learn
    learner = MultipleDatabaseLearner(newmln, dbs, method, **params)
  File "/home/dominik/.local/lib/python2.7/site-packages/pracmln/mln/learning/multidb.py", line 93, in __init__
    self.mln.weights = list(first(self.learners).mrf.mln.weights)
NameError: global name 'first' is not defined`

**Comment by kaivalyar** [comment]
Perhaps adding the following line to the start of the `multidb.py` file will solve your problem:
```
from first import first
```

Of course, this will require you to install the `first` package.
```
$ pip install first
```
You can refer to this [PyPI project link](https://pypi.org/project/first/) for more details.

**Comment by dieckmdo** [comment]
That fixed it, thanks.
