### ISSUE TITLE
installation error on mac osx 10.15.2

### ISSUE THREAD

**Issue by andreaBelmont** [danielnyga/pracmln#31]
Can anybody help on this installation error? Thanks

```
(py37) Jeeg:~ acortis$ pip install pracmln
Collecting pracmln
  Using cached https://files.pythonhosted.org/packages/fc/87/a4742276e4b5ec217ba0ed3148d0f2fe6f3190970a9e8f6e802daff7099f/pracmln-1.2.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/Caskroom/miniconda/base/envs/py37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t4/f39wd1sd25x8ry2hq74xhz1r0000gn/T/pip-install-d_silogh/pracmln/setup.py'"'"'; __file__='"'"'/private/var/folders/t4/f39wd1sd25x8ry2hq74xhz1r0000gn/T/pip-install-d_silogh/pracmln/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/t4/f39wd1sd25x8ry2hq74xhz1r0000gn/T/pip-install-d_silogh/pracmln/pip-egg-info
         cwd: /private/var/folders/t4/f39wd1sd25x8ry2hq74xhz1r0000gn/T/pip-install-d_silogh/pracmln/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t4/f39wd1sd25x8ry2hq74xhz1r0000gn/T/pip-install-d_silogh/pracmln/setup.py", line 13, in <module>
        pipmain(['install', 'appdirs'])
    TypeError: 'module' object is not callable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by cjen07** [comment]
https://github.com/cjen07/mln I think it may help

**Comment by andreaBelmont** [comment]
Thanks for your prompt response @cjen07 ... do you happen to know if pravmln is actively maintained?

**Comment by cjen07** [comment]
@andreaBelmont I don't know much about the maintainers, maybe too busy
