### ISSUE TITLE
import pracmln throws an error

### ISSUE THREAD

**Issue by ad71** [danielnyga/pracmln#7]
`>>> import pracmln` throws this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\pracmln\__init__.py", line 22, in <module>
    from .mln.base import MLN
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\pracmln\mln\__init__.py", line 27, in <module>
    from .base import MLN
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\pracmln\mln\base.py", line 27, in <module>
    from dnutils import logs, ifnone
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\dnutils\__init__.py", line 7, in <module>
    from .signals import add_handler, rm_handler, enable_ctrlc
  File "C:\Users\Aman Deep Singh\Anaconda3\lib\site-packages\dnutils\signals.py", line 11, in <module>
    SIGKILL = signal_.SIGKILL
AttributeError: module 'signal' has no attribute 'SIGKILL'

Did I miss something in setting up pracmln?
Is it not supported on Windows?

**Comment by cszipper** [comment]
According to [signal](https://docs.python.org/2/library/signal.html#signal.signal) docs
> On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, or SIGTERM. 

package [dnutils](https://github.com/danielnyga/dnutils) is not fully supported on Windows for now. You can simply remove some lines in `dnutils\signals.py`. If necessary, I can make a pull request to fix this.

**Comment by ad71** [comment]
Thanks for the clarification @cszipper ! It is not a problem as it is working on all flavors of Linux.
